/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.{html,js}", "./!(build|dist|.*)/**/*.{html,js}"],
  theme: {
    extend: {
      colors: {
        "dark-green": "#034249",
        "color-base-light": "#fff",
        back: "#768b8d",
        dimgray: {
          "100": "#776868",
          "200": "#5c7373",
        },
        filler: "#55858b",
        gray: {
          "100": "#141414",
          "200": "rgba(255, 255, 255, 0.2)",
        },
        "color-base-dark": "#262626",
        teal: "#36757d",
        main: "#5a5a5a",
        black: "#000",
        "color-base-borders": "#c6c6c6",
        "background-2": "#eee",
        lightgray: {
          "100": "#d5d5d5",
          "200": "#d4d4d4",
        },
        text: "#1c1c1c",
        gainsboro: "#e6e6e6",
        button: "#d9d9d9",
        "background-1": "#fbfbfb",
        button1: "#b6b6b6",
      },
      spacing: {
        "main-frame": "1920px",
        margins: "120px",
        "section-spacing-l": "120px",
        "paragraph-spacing-l": "24px",
        "section-spacing-s": "40px",
        "numbers-64": "64px",
        margins2: "120px",
        "numbers-80": "80px",
        "font-size-2xl": "64px",
        "section-spacing-m2": "80px",
        "paragraph-spacing-s": "12px",
        "section-spacing-xs": "24px",
        "numbers-16": "16px",
        "numbers-12": "12px",
        "paragraph-spacing-xl": "32px",
        "numbers-161": "16px",
        "section-spacing-m3": "80px",
        boundvariablesdata: "16px",
        boundvariablesdata1: "30px",
        boundvariablesdata2: "24px",
        boundvariablesdata3: "16px",
        boundvariablesdata4: "32px",
        boundvariablesdata5: "24px",
        boundvariablesdata6: "16px",
        boundvariablesdata8: "24px",
      },
      fontFamily: {
        para: "Inter",
        almarai: "Almarai",
        "dm-sans": "'DM Sans'",
        h5: "Archivo",
        para1: "'Work Sans'",
      },
      borderRadius: {
        "21xl": "40px",
        "3xs": "10px",
        "7xl": "26px",
        "11xl": "30px",
        xl: "20px",
        "81xl": "100px",
        "8xs": "5px",
        "radius-xs-2": "8px",
        "padding-xs": "4px",
      },
    },
    fontSize: {
      lg: "18px",
      "5xl": "24px",
      lgi: "19px",
      base: "16px",
      "9xl": "28px",
      "3xl": "22px",
      "13xl": "32px",
      "7xl": "26px",
      "29xl": "48px",
      "19xl": "38px",
      "10xl": "29px",
      xl: "20px",
      "15xl": "34px",
      "8xl": "27px",
      sm: "14px",
      inherit: "inherit",
    },
    screens: {
      mq1625: {
        raw: "screen and (max-width: 1625px)",
      },
      mq1275: {
        raw: "screen and (max-width: 1275px)",
      },
      mq900: {
        raw: "screen and (max-width: 900px)",
      },
      mq450: {
        raw: "screen and (max-width: 450px)",
      },
    },
  },
  corePlugins: {
    preflight: false,
  },
};
